name: 适配请求
description: 如果你有 某些需求/建议 请选择此项进行提交
title: "【适配请求】 应用名称"
labels: [ "新需求" ]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: ⚠️ 重要阅读
      options:
        - label: 由于个人时间精力有限 不会采纳所有的适配请求 具体更新请以最新版为准
          required: true
        - label: 可以提旧版模块上有的功能 会优先同步到新版模块
          required: true
        - label: 请勿提出任何一个APP的去广告功能 推荐使用模块 [@AdClose](https://github.com/zjyzip/AdClose)
          required: true
        - label: 提交应用前请动脑 你的需求是否合理 不要提出无理要求
          required: true
        - label: 不再提供微信功能 请不要再询问
          required: true
  - type: input
    id: app-name
    attributes:
      label: 应用名称
      description: 请在此填写您需要适配的应用名称
      placeholder: 例如：AppShare
    validations:
      required: true
  - type: input
    id: app-pkg
    attributes:
      label: 应用包名
      description: 请在此填写您需要适配的应用包名
      placeholder: 例如：info.muge.appshare
    validations:
      required: true
  - type: input
    id: app-size
    attributes:
      label: 应用大小
      description: 请在此填写应用安装包体积大小
      placeholder: 例如：28.41MB
    validations:
      required: true
  - type: input
    id: reinforcement
    attributes:
      label: 加固状态
      description: 请填写应用的加固状态(可以在MT管理器复制)
      placeholder: "例如：未加固/360加固/梆梆加固/网易易盾/等"
    validations:
      required: true
  - type: input
    id: app-use
    attributes:
      label: 应用用途
      description: 请在此填写您需要适配的应用用途
      placeholder: 例如：第三方应用商店
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
        label: 应用需求
        description: 请在此描述你的需求。
        placeholder: 需要去除开屏广告以及解锁本地会员
        render: text
    validations:
        required: true
  - type: textarea
    id: app-download
    attributes:
      label: 应用下载地址/安装包
      description: 请在此添加应用下载地址/安装包文件
    validations:
      required: true
  - type: textarea
    id: dex-unpack
    attributes:
      label: 脱壳任务提交 (如果已加固)
      description: 请前往 https://56.al/upload.php 上传对应应用的APK文件(方便我们更快为你适配)
      placeholder: "例如：https://56.al/file.php?hash=对应的hash值"
