name: "问题反馈"
description: "如果你有遇到 功能不生效/其他BUG 请选择此项进行反馈"
title: "【BUG反馈】 "
labels: [ "BUG" ]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: ⚠️ 重要阅读
      options:
        - label: 请确保你是LSPosed用户。
          required: true
        - label: 请确保你已升级至 [最新的release版本](https://github.com/Xposed-Modules-Repo/top.hookvip.pro/releases/latest)。
          required: true
        - label: 请确保你已在 [已有的issues](https://github.com/Xposed-Modules-Repo/top.hookvip.pro/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
          required: true
  - type: input
    id: xposed-framework
    attributes:
      label: 使用框架
      description: 请在此说明您使用的LSPosed框架分支
      placeholder: 例如：LSPosed-v1.9.2-7024-zygisk-release
    validations:
      required: true
  - type: input
    id: device-info
    attributes:
      label: 设备信息
      description: 请在此说明您使用的设备型号、Android 版本等信息
      placeholder: 例如：REDMI K80 PRO Android15
    validations:
      required: true
  - type: input
    id: app-name
    attributes:
      label: 应用名称
      description: 请在此说明要反馈的应用名称
      placeholder: 例如：AppShare
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: 应用版本号
      description: 请在此说明要反馈的应用版本信息
      placeholder: 例如：4.0.2(360)
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: 问题描述
      description: 请在此描述遇到的问题。
      render: text
    validations:
      required: true
  - type: textarea
    id: issues-screenshot
    attributes:
      label: 问题截图/视频
      description: 请在此上传问题的截图和视频。
    validations:
      required: true
  - type: textarea
    id: issues-lsposedlog
    attributes:
      label: LSPosed日志
      description: 请在此上传LSPosed的模块日志，提交前请先前往LSPosed管理器清空日志，然后重新复现此问题。
    validations:
      required: true
